databases:
  - name: uni-hub-db
    databaseName: uni_hub_production
    user: uni_hub
    plan: free

services:
  - type: web
    name: uni-hub
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: uni-hub-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_MAX_THREADS
        value: "1"
      - key: WEB_CONCURRENCY
        value: "1"
